# Generated by Django 3.0.3 on 2020-04-04 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_cargo_dependencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacto.Cargo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacto.Dependencia'),
        ),
    ]
