# Generated by Django 3.0.3 on 2020-04-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_auto_20200404_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='cargo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='dependencia',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Dependencia',
        ),
    ]
