# Generated by Django 3.0.3 on 2020-02-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cedula', models.DecimalField(decimal_places=0, max_digits=10)),
                ('ciudad', models.CharField(max_length=25)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=10)),
                ('mail', models.CharField(max_length=150)),
                ('profesion', models.CharField(max_length=50)),
                ('dependencia', models.CharField(max_length=40)),
                ('cargo', models.CharField(max_length=50)),
                ('archivo', models.FileField(upload_to='archivos/%Y/%m/%d')),
            ],
        ),
    ]
